project:
  type: website
  output-dir: docs
  resources: 
    - ads.txt

website:
  page-navigation: true
  title: "Mohammad Rafiqul Islam"
  favicon: "/_assets/images/favicon.ico"
  open-graph: true
  bread-crumbs: true
  back-to-top-navigation: true
  site-url: "https://mrislambd.github.io/" 
  twitter-card: true
  navbar:
    tools-collapse: true
    pinned: true
    logo: "/_assets/images/fsu-logo.png"
    logo-alt: "Florida State University"
    logo-href: index.qmd
    background: "#782F40"
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: portfolio.qmd
        text: Portfolio
      - href: cv.qmd
        text: CV
      - href: blog.qmd
        text: Blog
      - icon: linkedin
        href: https://www.linkedin.com/in/mohammad-rafiqul-islam/
        target: _blank
      - icon: github
        href: "https://github.com/mrislambd"
        target: _blank
      
      
  page-footer: 
    background: "#782F40"
    left: "Powered by [Quarto](https://quarto.org/) <?quarto.version?>"
    center:
      - text: "Copyright 2024 @ Rafiq Islam"
      - text: "License"
        href: license.txt
    right: 
      - icon: twitter 
        href: https://twitter.com/rafiqr35 
        target: _blank
      - icon: youtube
        href: https://youtube.com/@quanttube
        target: _blank
      

    border: true
  reader-mode: true


  # Google stuffs
  google-analytics: 
    tracking-id: "G-Z5NP67GHFC"
    anonymize-ip: true
adsense: 
  publisher-id: ca-pub-6878992848042528
filters:
  - adsense
  - quarto-version.lua
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid: 
      sidebar-width: 330px
    backgroundcolor: "#f4f4f4"
    linkcolor: "#782F40"
    code-copy: true
    code-overflow: wrap
    mainfont: lualatex
    code-fold: true 
    code-line-numbers: false
    code-tools: true
    minimal: false
    anchor-sections: true
    smooth-scroll: true
    
    
    



