---
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Proposition  
Let $V$ be a vector space and $\alpha \in End(V)$. Prove that if $V$ is finite-dimensional then $\alpha$ is injective if and only if $\alpha$ is surjective.  

## Proof:  
We will prove this by using the rank-nullity theorem which states that, "If $V$ and $W$ be two vector spaces over the field $\mathbb{F}$, where $V$ is finitely generated, then 

$\dim (V)=\dim (im(\alpha))+\dim (ker(\alpha))$   .... (*) 

where, $\alpha \in Hom(V,W)$.

$"\Rightarrow"$ 

Let $\{v_1,v_2, \cdots, v_n\}$ be a basis for $V$. So, any vector $v\in V$ can be represented as $v=\sum_{i=1}^{n}a_iv_i$ for some scalars $a_i \in \mathbb{F}$. 

Also suppose that, $\alpha \in End(V)$ is surjective. That is, $im(\alpha)=V \implies \dim (im(\alpha))= \dim (V)$. By (*) we see that $\dim (ker(\alpha))=0$. So we need to show $ker(\alpha)=\{0_V\}$ in order to show $\alpha$ is injective.

Since $\alpha$ is surjective, so

$\alpha(V)=V$

$\implies Span\{\alpha(v_1)\alpha(v_2),\cdots,\alpha(v_n)\}=V$

$\implies\{\alpha(v_1)\alpha(v_2),\cdots,\alpha(v_n)\}$ is also a basis for $V$. So, $\{\alpha(v_1)\alpha(v_2),\cdots,\alpha(v_n)\}$ is linearly independent.  Now,

$ker(\alpha)=\{v\in V| \alpha(v)=0_V\}$

$\, \, =\{v\in V| \alpha(\sum_{i=1}^{n}a_iv_i)=0\}$

$\,\, =\{v\in V| \sum_{i=1}^{n}a_i\alpha(v_i)=0\}$

Since, $\{\alpha(v_1)\alpha(v_2),\cdots,\alpha(v_n)\}$ is linearly independent, so $\sum_{i=1}^{n}a_i\alpha(v_i)=0 \implies a_i=0$ for $1 \le i \le n$. So,

$ker(\alpha)=\{0\}$.

Hence, $\alpha$ surjective $\implies$ $\alpha$ injective.

$"\Leftarrow"$

Now assume that $\alpha$ is injective. We need to show that $\alpha$ is surjective. Assume that,

$\sum_{i=1}^{n} a_i\alpha(v_i)=0$

$\implies \sum_{i=1}^{n} \alpha (a_iv_i)=0$

$\implies \alpha(\sum_{i=1}^{n} a_iv_i)=0$

 Now injectivity implies,

$ker(\alpha(v))=\{0_V\}$. So, $\sum_{i=1}^{n} a_iv_i=0$. But $\{v_1,v_2,\cdots,v_n\}$ is linearly independent. Therefore, $\sum_{i=1}^{n} a_iv_i=0 \implies a_i=0$. So, $\{\alpha(v_1)\alpha(v_2),\cdots,\alpha(v_n)\}$ is linearly independent in $V$. Since, $V$ has dimension $n$, so, $\{\alpha(v_1)\alpha(v_2),\cdots,\alpha(v_n)\}$ is a basis for $V$. 

Thus, $Span\{\alpha(v_1)\alpha(v_2),\cdots,\alpha(v_n)\}=im(\alpha)$. So, $\alpha$ is surjective.



Hence, for finite-dimensional vector space $V$ and $\alpha \in End(V)$, injective $\iff$ surjective.

## What if V is infinite-dimensional?  
Let say $V$ be the sequence space. That is $V=\{(a_n)_{n=1}^{\infty}: a_n \in \mathbb{F}\}$ and let $\alpha$ is defined as $\alpha: x=(a_n)_{n=1}^{\infty}\longrightarrow \{0,a_1,a_2,\cdots\}$.

So, in this case, $\alpha$ is one-to-one but not onto. That is, injectivity   is not implying surjectivity. Similarly, it can be shown that if the dimension is infinite then surectivity will not imply injectivity. 