---
title: "Spring 2025: MAC2311 Calculus With Analytic Geometry I"
collection: teaching
type: "Instructor of Record"
permalink: /teaching/2025-spring-teaching
venue: "Department of Mathematics, Florida State University"
date: 2025-05-04
location: "Tallahassee, Florida"
---  

<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6878992848042528"
     crossorigin="anonymous"></script>  


COURSE MEETING SCHEDULE:  

Mondays, Wednesdays, and Fridays  

Time: 10:40 AM - 11:30 AM
Location: HTL 215
Thursdays

Time: 11:35 AM - 12:50 PM
Location: HTL 215


CREDIT HOURS: 4

Time Zone: This course is a Main Campus FSU course and all times provided for this course (class meetings, due dates, etc) will be in Eastern Standard Time.

COURSE INSTRUCTOR


RAFIQ ISLAM  

rislam@fsu.edu

Office Hours: Monday 12:00-1:00, Tuesday 11:30-12:30, Wednesday  12:00 - 1:00 
Office: Lov 331


COURSE DESCRIPTION  

In this course, students will develop problem solving skills, critical thinking, computational proficiency, and contextual fluency through the study of limits, derivatives, and definite and indefinite integrals of functions of one variable, including algebraic, exponential, logarithmic, and trigonometric functions, and applications. Topics will include limits, continuity, differentiation and rates of change, optimization, curve sketching, and introduction to integration and area.

