---
title: "GJR-GARCH Volatility Modeling under NIG and ANN for Predicting Top Cryptocurrencies"
author: 
  - Fahad Mostafa
  - Pritam Saha
  - Mohammad Rafiqul Islam
  - Nguyet Nguyen
collection: publications
permalink: /publication/pub2
excerpt: 'This paper is about GJR-GARCH volatility modeling and cryptocurrencies'  
date: 2021-09-03  
citation:
  type: article-journal
  container-title: "Journal of Risk and Financial Management"
  doi: "10.3390/jrfm14090421"
  keyword: artificial neural network; cryptocurrency; GJR-GARCH; NIG; Monte Carlo simulation; value at risk backtesting 
  pdf-url: https://www.mdpi.com/1911-8074/14/9/421
bibliography: ../../biblio.bib
google-scholar: true
---  

<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6878992848042528"
     crossorigin="anonymous"></script>  

<p style="text-align: justify">
    Cryptocurrencies are currently traded worldwide, with hundreds of different currencies in existence and even more on the way. This study implements some statistical and machine learning approaches for cryptocurrency investments. First, we implement GJR-GARCH over the GARCH model to estimate the volatility of ten popular cryptocurrencies based on market capitalization: Bitcoin, Bitcoin Cash, Bitcoin SV, Chainlink, EOS, Ethereum, Litecoin, TETHER, Tezos, and XRP. Then, we use Monte Carlo simulations to generate the conditional variance of the cryptocurrencies using the GJR-GARCH model, and calculate the value at risk (VaR) of the simulations. We also estimate the tail-risk using VaR backtesting. Finally, we use an artificial neural network (ANN) for predicting the prices of the ten cryptocurrencies. The graphical analysis and mean square errors (MSEs) from the ANN models confirmed that the predicted prices are close to the market prices. For some cryptocurrencies, the ANN models perform better than traditional ARIMA models.
</p>

Download the paper from [here](/publication/pub2/paper2.pdf)  

**Share on**  

<div id="fb-root"></div>
<script async defer crossorigin="anonymous"
 src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v20.0"></script>
 
<div class="share-buttons">
<div class="fb-share-button" data-href="https://mrislambd.github.io/publication/pub2/"
data-layout="button_count" data-size="small"><a target="_blank" 
 href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fmrislambd.github.io%2Fpublication%2Fpub2%2F&amp;src=sdkpreparse" 
 class="fb-xfbml-parse-ignore">Share</a></div>

<script src="https://platform.linkedin.com/in.js" type="text/javascript">lang: en_US</script>
<script type="IN/Share" data-url="https://mrislambd.github.io/publication/pub2/"></script> 
 
<a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" 
 data-url="https://mrislambd.github.io/publication/pub2/" data-show-count="true">Tweet</a>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>





